WITH FILL_RATE_RAW_DATA AS(

SELECT 
	DISTINCT
	CAST(SL.MODIFYTS AS DATE) MODIFYTS,
	SL.ORDER_NO,
	SL.ITEM_ID,
	S.SHIPNODE_KEY,
	--store.District_ID,
	--store.Region_ID,
	--ORS.STATUS,
	--ORDER_STATUS.DESCRIPTION,
	SL.ORDER_LINE_KEY,
	--ORS.STATUS_QUANTITY,
	SL.ORIGINAL_QUANTITY,
	SL.QUANTITY PICKED_QUANTITY,
	--SL.EXTN_SHORTAGE_REASON,
	SL.SHORTAGE_QTY,
	FISCAL_DATE.FISCAL_WEEK_ID FISCAL_WEEK
FROM 
	"WHPRD_VW"."DWADMIN"."F_OMS_YFS_SHIPMENT_LINE" SL,
	(SELECT * FROM "WHPRD_VW"."DWADMIN"."F_OMS_YFS_SHIPMENT") S,
	(SELECT * FROM "WHPRD_VW"."DWADMIN"."F_OMS_YFS_ORDER_RELEASE_STATUS" WHERE STATUS_QUANTITY > 0) ORS,
	(SELECT * FROM "WHPRD_VW"."DWADMIN"."FT_CUST_ORDER_LINE" WHERE DELIVERY_METHOD = 'PICK' AND BUNDLE_PARENT_ORDER_LINE_KEY IS NULL) OL,
	(select trim(DESCRIPTION) as DESCRIPTION, STATUS from "WHPRD_VW"."DWADMIN"."F_OMS_YFS_STATUS" where PROCESS_TYPE_KEY='ORDER_FULFILLMENT') Order_status,
	--"WHPRD_VW"."DWADMIN"."LU_STORE" store,
	(SELECT * FROM "WHPRD_VW"."DWADMIN"."LU_DATE" WHERE DAY_ID > '2018-05-01 00:00:00') FISCAL_DATE
WHERE
	SL.ORDER_LINE_KEY = ORS.ORDER_LINE_KEY
	--AND store.LOC_ID = S.SHIPNODE_KEY
	AND FISCAL_DATE.DAY_ID = CAST(SL.MODIFYTS AS DATE)
	AND SL.ORDER_LINE_KEY = OL.ORDER_LINE_KEY
	AND SL.SHIPMENT_KEY = S.SHIPMENT_KEY
	AND ORDER_STATUS.STATUS = ORS.STATUS
	AND ORS.STATUS IN('9000','3700.01.100' , '3700.01.200','3700.01','3700.02')
	
	--AND S.SHIPNODE_KEY = '196'
	--AND SL.ORDER_NO = '53299807'
	--AND ORS.STATUS
),

ORDER_COUNT AS(


SELECT 
	COUNT(DISTINCT OH.ORDER_NO) ORDER_COUNT,
	CAST(OH.CREATETS AS DATE) OMS_DATE
FROM 
	"WHPRD_VW"."DWADMIN"."FT_CUST_ORDER_LINE" OL,
	"WHPRD_VW"."DWADMIN"."FT_CUST_ORDER_HEADER" OH
WHERE
	OL.ORDER_HEADER_KEY = OH.ORDER_HEADER_KEY
	--AND OMS_DATE between '2018-05-02 00:00:00' and '2018-05-04 00:00:00'
	AND OL.DELIVERY_METHOD = 'PICK'
	AND oh.enterprise_key = 'PETCOCOMUS'	
	AND oh.DOCUMENT_TYPE = '0001'	
GROUP BY
	OMS_DATE
ORDER BY
    OMS_DATE

)

SELECT 
	CAST(FILL_RATE_RAW_DATA.MODIFYTS AS DATE) as MODIFYTS,
	ORDER_COUNT.ORDER_COUNT,
	--FILL_RATE_RAW_DATA.SHIPNODE_KEY,
	--FILL_RATE_RAW_DATA.FISCAL_WEEK,
	SUM (FILL_RATE_RAW_DATA.PICKED_QUANTITY) STORE_RECEIVED_QTY,
	SUM (FILL_RATE_RAW_DATA.SHORTAGE_QTY) SHORTAGE_QUANTITY,
	(STORE_RECEIVED_QTY   * 100.00 / NULLIF((STORE_RECEIVED_QTY + SHORTAGE_QUANTITY),0)) FILL_RATE
FROM 

	FILL_RATE_RAW_DATA,
	ORDER_COUNT
	
WHERE
	ORDER_COUNT.OMS_DATE = FILL_RATE_RAW_DATA.MODIFYTS
	--MODIFYTS BETWEEN ''
GROUP BY 
	
	--FILL_RATE_RAW_DATA.FISCAL_WEEK
	FILL_RATE_RAW_DATA.MODIFYTS,
	ORDER_COUNT.ORDER_COUNT
	--FILL_RATE_RAW_DATA.SHIPNODE_KEY
	
ORDER BY 
	MODIFYTS
	--FILL_RATE_RAW_DATA.FISCAL_WEEK