-- vendor report 
SELECT SKU_ID, LOC_ID, ONHANDSUPPLY
FROM "WHPRD_VW"."DWADMIN"."F_YIH_SHIP_ATP" WHERE (SKU_ID,LOC_ID,RECORDS_CREATE_TS) IN 
( SELECT SKU_ID,LOC_ID, MAX(RECORDS_CREATE_TS)
  FROM "WHPRD_VW"."DWADMIN"."F_YIH_SHIP_ATP"
  WHERE LOC_ID LIKE 'V_%'
  GROUP BY SKU_ID,LOC_ID
)